### ISSUE TITLE
cannot start backed service

### ISSUE THREAD

**Issue by lqjack** [velopert/whotalk.us#4]
when i execute `npm start` , i get the response as blow : 

> whotalk-backend@1.0.0 start /Users/liu/node/whotalk.us/whotalk-backend
> node build

Cache is initialized
/Users/liu/node/whotalk.us/whotalk-backend/build/models/follow.js:30
Follow.statics.follow = function ({ followee, follower }) {
                                  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/liu/node/whotalk.us/whotalk-backend/build/routes/authentication.js:31:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/liu/node/whotalk.us/whotalk-backend/build/routes/index.js:11:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/liu/node/whotalk.us/whotalk-backend/build/index.js:39:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whotalk-backend@1.0.0 start: `node build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whotalk-backend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liu/.npm/_logs/2017-09-17T14_58_35_405Z-debug.log

**Comment by happyname0617** [comment]
maybe you could try with "npm run dev" for backend server. "npm start" is the command for front-end in the documentation.

**Comment by velopert** [comment]
same as what happyname0617 has written. Sorry for late response.

**Comment by lqjack** [comment]
thanks a lot . the error disappeared.
but i get the message as below : 
> whotalk-frontend@0.0.1 start /Users/liu/node/whotalk.us/whotalk-frontend
> node ./scripts/start.js
Starting the development server...
Failed to compile.

Error in Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
 @ ./src/styles/main.scss 4:14-155 13:2-17:4 14:20-161
